#!/bin/bash
if [ -z "$1" ]; then
	echo "Usage: /start core_ip core_port irc_server irc_port irc_chan irc_nick";
	echo "Please do not include the # when specifying the irc chan.";
else
	python ./src/core/server.py $1 $2 &
	echo "database = 'relae.db'" > ./src/irc/config.py
	echo "server = '$3'" >> ./src/irc/config.py
	echo "portno = $4" >> ./src/irc/config.py
	echo "channel = '$5'" >> ./src/irc/config.py
	echo "nickname = '$6'" >> ./src/irc/config.py
	echo "password = ''" >> ./src/irc/config.py
	echo "relae_ip = '$1'" >> ./src/irc/config.py
	echo "relae_port = $2" >> ./src/irc/config.py
	python ./src/irc/ircbot.py &
fi
